### PR TITLE
[82] Removed .travis.yml from project.

### LINKED ISSUE #82: Remove '.travis.yml' from project.
Remove legacy file.

### PR DESCRIPTION
**Pull request by gffbss**
Closes: #82

### CODE REVIEW

**Comment by elbenfreund** [comment]
Welcome Geoffrey. Thank you for your PR.
I have a deadline coming up this week, so I won't be able to address it right away, but we should be able to merge it by the end of the week.
I hope you don't mind, I adjusted its title and body to reflect our general structure and to play nice with waffle.io.
Are you just passing by or potentially interested in some general cooperation?

**Comment by elbenfreund** [comment]
We very much appreciate your contribution and would love to encourage further work with us. This particular PR was closed without merge however as we have moved from codeship to Travis-CI. See #90 for details.
Hope to see you around, Eric.

**Comment by gffbss** [comment]
Great, thank you Eric. I am trying to level up my open source contribution skills and would be happy to continue to contribute. I will take a look at some of the other issues and see if I can't tackle something.

Geoff

**Comment by elbenfreund** [comment]
That is great to hear. Right now ``hamster_cli`` is in a bit of a rough state, as the currently packaged version isn't working to well. We will have to set up a proper config-creation/locate routine so it works in a packaged environment. Unfortunately this wont be ready till the beginning of next week, but after that I think you will finde this a rewarding project to contribute to with a wide range of skill level requirements.

**Pull request closed without merging**
